### PR TITLE
Changes to make Spotify work

### PR DESCRIPTION
**Pull request by gcampax**
For the demo 9/3

### CODE REVIEW

**Comment by tete2soja** [comment]
Hello,

I'm trying to connect to Spotify but each time, I have a 400 error:

Sorry that did not work
Unexpected HTTP error 400 in request to https://accounts.spotify.com/api/token

```
HTTP request failed: {"error":"invalid_grant","error_description":"Invalid redirect URI"}
Error obtaining access token HTTPError: Unexpected HTTP error 400 in request to https://accounts.spotify.com/api/token
    at IncomingMessage.<anonymous> (/opt/genie-server/node_modules/thingpedia/dist/helpers/http.js:142:35)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 400,
Error: Unexpected HTTP error 400 in request to https://accounts.spotify.com/api/token
    at oauthPart2 (/opt/genie-server/node_modules/thingpedia/dist/helpers/oauth2.js:196:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  url: 'https://accounts.spotify.com/api/token',
  detail: '{"error":"invalid_grant","error_description":"Invalid redirect URI"}'
}
```
Thanks!

**Comment by gcampax** [comment]
Hello, this is not really the right place to discuss it (this PR was long merged), but what version of Genie is this? How did you install?

**Comment by tete2soja** [comment]
Oh. sorry. I was writing here after click on an issue. I didn't pay attention. Sorry.

I used the lasted available on Home Assistant add-on repository since I wanted to use it with HA. So, the version use now is `edge-3d0c903`.

**Comment by gcampax** [comment]
Thank you for the report, that was indeed a configuration issue on our end, it should be fixed now.

**Pull request merged**
